name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: self-hosted
    
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        sudo yum install python-pip
        sudo pip install --upgrade pip

    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py
